spring.application.name=aid-link

spring.datasource.url=jdbc:mysql://root:koJqipEHSyafykUIHlnjdnvzEukOClwu@switchback.proxy.rlwy.net:24772/railway
spring.datasource.username=root
spring.datasource.password=koJqipEHSyafykUIHlnjdnvzEukOClwu

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080